apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: name-

commonLabels:
  app: name

images:
  - name: replace-me
    newName: fassmus/name-service
    newTag: v1.1.1