apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: hello-

namespace: telepresence

commonLabels:
  app: hello

configMapGenerator:
  - name: hello-cfg
    files:
      - config/my-config.txt

patchesStrategicMerge:
  - deploy-patch.yaml

images:
  - name: replace-me
    newName: fassmus/hello-service
    newTag: v1.1.2